sudo: required

language: python

services:
    - docker

before_deploy:
    - docker build -t sarataha/testapp:$TRAVIS_TAG ./app

deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        tags: true
